#%RAML 1.0

title: Event config
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Event config API
    content: This module contains information describing the notification events

types:
  errors: !include raml-util/schemas/errors.schema
  eventEntity: !include event_entity.json
  eventResponse: !include event_response.json

traits:
  validate: !include raml-util/traits/validation.raml

/eventConfig:
  post:
    description: Create new event config in storage
    body:
      application/json:
        schema: eventEntity
    responses:
      201:
        description: "created"
        body:
          application/json:
            schema: eventEntity
      400:
        description: "Bad request"
        body:
          text/plain:
            example: "Bad request"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  /{id}:
    get:
      description: Get event config from storage
      responses:
        200:
          description: "success"
          body:
            application/json:
              schema: eventEntity
        404:
          description: "Not found"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    put:
      description: Update event config in storage
      body:
        application/json:
          schema: eventEntity
      responses:
        200:
          description: "success"
          body:
            application/json:
              schema: eventEntity
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    delete:
      description: Delete event config from storage
      responses:
        200:
          description: "success"
          body:
            application/json:
              schema: eventResponse
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
